AllCops:
  TargetRubyVersion: 3.0.0

Gemspec/RequiredRubyVersion:
  Enabled: false

Documentation:
  Enabled: false

Bundler/DuplicatedGem:
  Enabled: true

Bundler/InsecureProtocolSource:
  Enabled: true

Layout/ClassStructure:
  Enabled: true

Layout/LineLength:
  Enabled: true
  AutoCorrect: true
  Max: 120

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/LeadingEmptyLines:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ShadowedArgument:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: true
  IgnoredMethods: [
    'print', 'puts', 'raise', 'require',
  ]
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  EnforcedStyle: require_parentheses

Style/MutableConstant:
  Enabled: true
  EnforcedStyle: literals

Style/TrailingCommaInArguments:
  Enabled: comma
